% jinzhengtao
% time:2024/11/28
% 修改内容：将8通道的NOMP算法设置参数扩展到64通道

%% 曾经过去的全部设置

noise_level = 1e-8;

N_fft    = 4096;%64;                                              % FFT point
f_subcar = 30e3;%312.5e3;                                         % subcarrier spacing载波间隔
f_sample = f_subcar*N_fft;                                  % bandwidth 带宽 也是采样频率
n_sample = [-N_fft/2:N_fft/2-1].'/N_fft;                    % n/N = [-32:-1 0:31] / 64
% 取负数是为了使得频谱的中心在0 Hz的位置，这是为了方便在通信系统中进行频域处理。
% 当FFT变换后，输出的频域数据从0 Hz开始，直到采样频率的一半（也就是Nyquist频率），
% 而对于OFDM系统来说，我们一般希望将信号分布在整个带宽内，因此，我们可以将频谱的中心设置在0 Hz的位置。
sub_num = 3276;%52;                                               % number of subcarrier
sub_loc = [N_fft/2-ceil(sub_num/2)+1 : N_fft/2 ...          % subcarrier index
               N_fft/2+2 : N_fft/2+floor(sub_num/2)+1];   
% sub_loc = [N_fft/2-ceil(sub_num/2)+1 : N_fft/2 ...          % subcarrier index
%                N_fft/2+1 : N_fft/2+floor(sub_num/2)];   

clear f_subcar sub_num


%% 2D ideal triangular antenna estimation
antPosition = [ [      -31.5        ;        0       ], ...
                [      -30.5        ;        0       ], ...
                [      -29.5        ;        0       ], ...
                [      -28.5        ;        0       ], ...
                [      -27.5        ;        0       ], ...
                [      -26.5        ;        0       ], ...
                [      -25.5        ;        0       ], ...
                [      -24.5        ;        0       ], ...
                [      -23.5        ;        0       ], ...
                [      -22.5        ;        0       ], ...
                [      -21.5        ;        0       ], ...
                [      -20.5        ;        0       ], ...
                [      -19.5        ;        0       ], ...
                [      -18.5        ;        0       ], ...
                [      -17.5        ;        0       ], ...
                [      -16.5        ;        0       ], ...
                [      -15.5        ;        0       ], ...
                [      -14.5        ;        0       ], ...
                [      -13.5        ;        0       ], ...
                [      -12.5        ;        0       ], ...
                [      -11.5        ;        0       ], ...
                [      -10.5        ;        0       ], ...
                [       -9.5        ;        0       ], ...
                [       -8.5        ;        0       ], ...
                [       -7.5        ;        0       ], ...
                [       -6.5        ;        0       ], ...
                [       -5.5        ;        0       ], ...
                [       -4.5        ;        0       ], ...
                [       -3.5        ;        0       ], ...
                [       -2.5        ;        0       ], ...
                [       -1.5        ;        0       ], ...
                [       -0.5        ;        0       ], ...
                [        0.5        ;        0       ], ...
                [        1.5        ;        0       ], ...
                [        2.5        ;        0       ], ...
                [        3.5        ;        0       ], ...
                [        4.5        ;        0       ], ...
                [        5.5        ;        0       ], ...
                [        6.5        ;        0       ], ...
                [        7.5        ;        0       ], ...
                [        8.5        ;        0       ], ...
                [        9.5        ;        0       ], ...
                [       10.5        ;        0       ], ...
                [       11.5        ;        0       ], ...
                [       12.5        ;        0       ], ...
                [       13.5        ;        0       ], ...
                [       14.5        ;        0       ], ...
                [       15.5        ;        0       ], ...
                [       16.5        ;        0       ], ...
                [       17.5        ;        0       ], ...
                [       18.5        ;        0       ], ...
                [       19.5        ;        0       ], ...
                [       20.5        ;        0       ], ...
                [       21.5        ;        0       ], ...
                [       22.5        ;        0       ], ...
                [       23.5        ;        0       ], ...
                [       24.5        ;        0       ], ...
                [       25.5        ;        0       ], ...
                [       26.5        ;        0       ], ...
                [       27.5        ;        0       ], ...
                [       28.5        ;        0       ], ...
                [       29.5        ;        0       ], ...
                [       30.5        ;        0       ], ...
                [       31.5        ;        0       ]
                ];      % antenna position (unit: half-wavelength)

% antPosition = [ [       -0.5        ;        0       ], ...
%                 [        0.5        ;        0       ], ...
%                 ];      % antenna position (unit: half-wavelength)
            
            
% AZ_Table = [0:1:360-1];                                     % azimuth   方位角
AZ_Table = [0:1:180-1];                                     % azimuth   方位角
EL_Table = 0;                                               % elevation 俯仰角

a = repmat(EL_Table,length(AZ_Table),1); % a:180*1                   % all AOA = [elevation azimuth]
AOATable = [];
AOATable(:,1) = a(:);
AOATable(:,2) = repmat(AZ_Table',length(EL_Table),1); % 180*1,AOATable:180*2
phase_table = Steering(antPosition, AOATable/180*pi);

set_triangular_2D.Nr          = size(antPosition,2);        % number of antenna
set_triangular_2D.antPosition = antPosition;                % for generating channel
set_triangular_2D.AOATable    = AOATable;                   % for estimation
set_triangular_2D.phase_table = phase_table;                % for estimation

clear a antPosition AOATable AZ_Table EL_Table phase_table